# This is a registry of literal parameters that can be used as node inputs.
#
# When defining node inputs in the pipeline, you can reference keys from this yaml to indicate
# that the pipeline should map the literal defined here to the node's input at runtime.
#
# Kedro precedent defines that the keys in this yaml can be referenced as below when defining
# node inputs:
# e.g. "params:my_key_1", "params:my_key_2.my_sub_key_2"

setup:
  use_case:
    name: 
  datasets:
    timeseries_dataset_name: Weather Time Series Data 
  locations:
    Boston:
      Latitude: 42.3584
      Longitude: -71.0598
    San Francisco:
      Latitude: 37.7749
      Longitude: -122.4194
    Columbus:
      Latitude: 39.9612
      Longitude: -82.9988
    Washington DC:
      Latitude: 38.8951
      Longitude: -77.0364
    Pittsburgh:
      Latitude: 39.6295
      Longitude: -79.9559
    Copenhagen:
      Latitude: 55.6759
      Longitude: 12.5655
    Kyiv:
      Latitude: 50.4547
      Longitude: 30.5238
    London:
      Latitude: 51.5085
      Longitude: -0.1257
    Singapore:
      Latitude: 1.2897
      Longitude: 103.8501
    Tokyo:
      Latitude: 35.6895
      Longitude: 139.6917
  weather_parameters:
    hourly: # You can find more parameters here: https://open-meteo.com/en/docs
      - temperature_2m
      - precipitation_probability
      - precipitation
      - uv_index
    temperature_unit: fahrenheit
    timezone: auto
    past_days: 1
    forecast_days: 0

preprocessing:
  use_case:
    name: 
  datasets:
    timeseries_dataset_name: Weather Raw Time Series Data
    modeling_dataset_name: Weather Modeling Data

deploy_forecast:
  use_case:
    name: 
  dataset_name: Weather Modeling Data
  project:
    name: {{ cookiecutter.project_name }} Project 
    analyze_and_model_config:
      metric: RMSE
      mode: quick
      target: viewDiff
      worker_count: 12
    datetime_partitioning_config:
      datetime_partition_column: date
      multiseries_id_columns: [city]
      use_time_series: true
      feature_derivation_window_start: -48 # Forecast/Feature Derivation Window start/ends must be a multiple of the time step
      feature_derivation_window_end: 0
      forecast_window_start: 1
      forecast_window_end: 12
      # default_to_known_in_advance: true
    advanced_options_config:
      seed: 42
  registered_model:
    name: {{ cookiecutter.project_name }}
  deployment:
    label: {{ cookiecutter.project_name }}
    description: A fantastically generated forecast from Kedro, hurray!
    prediction_interval: 80
    # association_id_column_name: association_id
  retraining_policy:
    name: Retrain on Accuracy Decline
    retraining_settings:
      autopilotOptions:
        blendBestModels: false
        mode: quick
        shapOnlyMode: false
        runLeakageRemovedFeatureList: true
      trigger:
        type: accuracy_decline
        schedule:
          minute:
          - 0
          hour:
          - 0
          dayOfMonth:
          - '*'
          month:
          - '*'
          dayOfWeek:
          - '*'
        statusDeclinesToWarning: true
        statusDeclinesToFailing: false
        statusStillInDecline: false
      projectOptions:
        cvMethod: RandomCV
        validationType: CV
        reps:
        validationPct:
        holdoutPct:
        metric: RMSE
      featureListStrategy: informative_features
      projectOptionsStrategy: same_as_champion
      modelSelectionStrategy: autopilot_recommended
      action: model_replacement
  batch_prediction_job_definition:
    batch_prediction_job:
      num_concurrent: 3
      intake_settings:
        type: dataset
    enabled: true
    schedule:
      minute:
      - 0
      hour:
      - 0
      - 3
      - 6
      - 9
      - 12
      - 15
      - 18
      dayOfMonth:
      - '*'
      month:
      - '*'
      dayOfWeek:
      - '*'
    name: Batch Prediction Job for Retraining


deploy_streamlit_app:
  prediction_dataset_name: Weather Modeling Data
  custom_app_name: {{ cookiecutter.project_name }} Streamlit
  environment_name: {{ cookiecutter.project_name }} Streamlit Environment
  environment_use_cases:
  - customApplication
  page_title: Weather Forecasting
  graph_y_axis: Increase in Views
  lower_bound_forecast_at_0: true
  headline:
    temperature: 0.2
    prompt: |
      You are a meteorologist. Explain to non-technical clients what this data suggests.
      Executive leadership will provide a forecast and you will interpret it and summarize the outlook, highlighting key insights.                         
      Your response should be only 1 sentence long, not very wordy. It should be like a news headline. Do not put quotation marks around it.
      Your response, while insightful, should speak to the general direction of the forecast.
      Even if you're unsure, speak with confidence and certainty.
  analysis:
    temperature: 0.0