# This is a registry of literal parameters that can be used as node inputs.
#
# When defining node inputs in the pipeline, you can reference keys from this yaml to indicate
# that the pipeline should map the literal defined here to the node's input at runtime.
#
# Kedro precedent defines that the keys in this yaml can be referenced as below when defining
# node inputs:
# e.g. "params:my_key_1", "params:my_key_2.my_sub_key_2"

get_data_pipeline:
  use_case:
    name: {{ cookiecutter.project_name }} # TODO: write in README that usecase must be same name as project
  playlist_ids:
    - PLSdoVPM5WnndLX6Ngmb8wktMF61dJirKl
    - PLFzMBB6IQkE4_BZDBRPtxNEafeGdDFDqV
  timeseries_dataset_name: {{ cookiecutter.project_name }} Raw Time Series Data
  metadataset_name: {{ cookiecutter.project_name }} Meta Data
  combined_dataset_name: {{ cookiecutter.project_name }} Modeling Data

deploy_forecast:
  use_case:
    name: {{ cookiecutter.project_name }}
  dataset_name: {{ cookiecutter.project_name }} Modeling Data
  project:
    name: {{ cookiecutter.project_name }} Project 
    analyze_and_model_config:
      metric: RMSE
      mode: quick
      target: viewCount
      worker_count: 12
    datetime_partitioning_config:
      datetime_partition_column: "as_of_datetime" #TODO: in the get_data pipeline, can I put a cookiecutter as the datetime_partition column?
                                                # I'm worried that the user may have to change too many things at this stage.
      multiseries_id_columns: [video_id]
      use_time_series: True
      feature_derivation_window_start: -35
      feature_derivation_window_end: 0
      forecast_window_start: 1
      forecast_window_end: 24
      # TODO: what other configurations should we add? Should we add and leave empty?
      #   - Known in advance?
    advanced_options_config:
      seed: 42
  registered_model:
    name: {{ cookiecutter.project_name }}
  deployment:
    label: {{ cookiecutter.project_name }}
    description: A fantastically generated forecast from Kedro, hurray!
    prediction_interval: 80