# This is a registry of literal parameters that can be used as node inputs.
#
# When defining node inputs in the pipeline, you can reference keys from this yaml to indicate
# that the pipeline should map the literal defined here to the node's input at runtime.
#
# Kedro precedent defines that the keys in this yaml can be referenced as below when defining
# node inputs:
# e.g. "params:my_key_1", "params:my_key_2.my_sub_key_2"

get_data_pipeline:
  use_case:
    name: {{ cookiecutter.project_name }} # TODO: write in README that usecase must be same name as project
  playlist_ids:
    - 
    -
    -
  timeseries_dataset_name: {{ cookiecutter.project_name }} Raw Time Series Data
  metadataset_name: {{ cookiecutter.project_name }} Meta Data

preprocessing:
  use_case:
    name: {{ cookiecutter.project_name }}
  timeseries_dataset_name: {{ cookiecutter.project_name }} Raw Time Series Data
  metadataset_name: {{ cookiecutter.project_name }} Meta Data
  modeling_dataset_name: {{ cookiecutter.project_name }} Modeling Data
  scoring_dataset_name: {{ cookiecutter.project_name }} Scoring Data

deploy_forecast:
  use_case:
    name: {{ cookiecutter.project_name }}
  dataset_name: {{ cookiecutter.project_name }} Modeling Data
  project:
    name: {{ cookiecutter.project_name }} Project 
    analyze_and_model_config:
      metric: RMSE
      mode: quick
      target: viewDiff
      worker_count: 12
    datetime_partitioning_config:
      datetime_partition_column: as_of_datetime
      multiseries_id_columns: [title]
      use_time_series: True
      forecast_window_start: 3 # Forecast Window start must be a multiple of the time step
      forecast_window_end: 6
      # TODO: what other configurations should we add? Should we add and leave empty?
      #   - Known in advance?
    advanced_options_config:
      seed: 42
  registered_model:
    name: {{ cookiecutter.project_name }}
  deployment:
    label: {{ cookiecutter.project_name }}
    description: A fantastically generated forecast from Kedro, hurray!
    prediction_interval: 80

deploy_streamlit_app:
  custom_app_name: {{ cookiecutter.project_name }} Streamlit
  environment_name: {{ cookiecutter.project_name }} Streamlit Environment
  environment_use_cases:
    - customApplication
  page_title: Music Video Forecast
  graph_y_axis: Increase in Views
  lower_bound_forecast_at_0: True
  headline:
    temperature: 0.2
    prompt: |
      You are a data analyst. Explain to non-technical executives business leaders what this data suggests.
      Executive leadership will provide a forecast and you will interpret it and summarize the outlook, highlighting key insights.                         
      Your response should be only 1 sentence long, not very wordy. It should be like a news headline. Do not put quotation marks around it.
      Your response, while insightful, should speak to the general direction of the forecast.
      Even if you're unsure, speak with confidence and certainty.
  analysis:
    temperature: 0.0