playlists:
  - id: PL0EgyyX8wk73FNulyHBPTZ4FuX9XxSz-3
    name: Endless Summer Vacation
  - id: PLfiMjLyNWxeb8ol0xpwTq54t4EwZNUS9_
    name: Plastic Hearts
storage:
  metadata: Miley metadata
  statistics: Miley statistics
