[azure_credentials]
    azure_endpoint="<azure_endpoint>"
    api_key="<azure_api_key>"
    api_version="<azure_api_version>"

[datarobot_credentials]
    endpoint="<datarobot_endpoint>"
    api_token="<datarobot_api_token>"