# This is a registry of literal parameters that can be used as node inputs.
#
# When defining node inputs in the pipeline, you can reference keys from this yaml to indicate
# that the pipeline should map the literal defined here to the node's input at runtime.
#
# Kedro precedent defines that the keys in this yaml can be referenced as below when defining
# node inputs:
# e.g. "params:my_key_1", "params:my_key_2.my_sub_key_2"

get_data_pipeline:
  use_case:
    name: 
  playlist_ids:
    - 
    -
  # Note: if you change any of the dataset names here, make sure they remain the same across all of your codespaces
  timeseries_dataset_name: Music Video Raw Time Series Data 
  metadataset_name: Music Video Meta Data

preprocessing:
  use_case:
    name: 
  timeseries_dataset_name: Music Video Raw Time Series Data
  metadataset_name: Music Video Meta Data
  modeling_dataset_name: Music Video Modeling Data
  scoring_dataset_name: Music Video Scoring Data

deploy_forecast:
  use_case:
    name: 
  dataset_name: Music Video Scoring Data
  project:
    name: {{ cookiecutter.project_name }} Project 
    analyze_and_model_config:
      metric: RMSE
      mode: quick
      target: viewDiff
      worker_count: 12
    datetime_partitioning_config:
      datetime_partition_column: as_of_datetime
      multiseries_id_columns: [title]
      use_time_series: True
      # Forecast/Feature Derivation Window start/ends must be a multiple of the time step
      feature_derivation_window_start: -21 
      feature_derivation_window_end: 0
      forecast_window_start: 3 
      forecast_window_end: 36
      # TODO: what other configurations should we add? Should we add and leave empty?
      #   - Known in advance?
    advanced_options_config:
      seed: 42
  registered_model:
    name: {{ cookiecutter.project_name }}
  deployment:
    label: {{ cookiecutter.project_name }}
    description: A fantastically generated forecast from Kedro, hurray!
    prediction_interval: 80
    association_id_column_name: "association_id"
  retraining_policy:
    name: Retrain on Accuracy Decline
    kwargs:
      autopilotOptions:
        blendBestModels: false
        mode: quick
        shapOnlyMode: false
        runLeakageRemovedFeatureList: True
      trigger:
        type: accuracy_decline
        statusDeclinesToWarning: true,
        statusDeclinesToFailing: false
        statusStillInDecline: false
      featureListStrategy: informative_features
      projectOptionsStrategy: same_as_champion
      modelSelectionStrategy: autopilot_recommended
    action: model_replacement
  batch_prediction_job_definition:
    batch_prediction_job:
      intake_settings: 
        type: dataset
        dataset: 
    enabled: True
    name: Batch Prediction Job for Retraining


deploy_streamlit_app:
  scoring_dataset_name: Music Video Scoring Data
  custom_app_name: {{ cookiecutter.project_name }} Streamlit
  environment_name: {{ cookiecutter.project_name }} Streamlit Environment
  environment_use_cases:
    - customApplication
  page_title: Music Video Forecasting
  graph_y_axis: Increase in Views
  lower_bound_forecast_at_0: True
  headline:
    temperature: 0.2
    prompt: |
      You are a data analyst. Explain to non-technical clients what this data suggests.
      Executive leadership will provide a forecast and you will interpret it and summarize the outlook, highlighting key insights.                         
      Your response should be only 1 sentence long, not very wordy. It should be like a news headline. Do not put quotation marks around it.
      Your response, while insightful, should speak to the general direction of the forecast.
      Even if you're unsure, speak with confidence and certainty.
  analysis:
    temperature: 0.0